input_group {
    "Parametros",
    MIN_VOTES   = input(6,    "Min votes",          input.integer,   1,  10, 1),
    MIN_CANDLES = input(15,   "Min candles",        input.integer,   1,  10, 1),
    BB_PER      = input(26,   "BB period",          input.integer,   5, 100, 1),
    BB_MULT     = input(2.03, "BB multiplier",      input.double,    0.5, 4, 0.01),
    EMA_FAST    = input(36,   "EMA fast",            input.integer,   1, 100, 1),
    EMA_SLOW    = input(156,  "EMA slow",            input.integer,   2, 200, 1),
    RSI_PER     = input(22,   "RSI period",          input.integer,   2, 100, 1),
    RSI_BUY     = input(58,   "RSI buy threshold",   input.integer,   0, 100, 1),
    RSI_SELL    = input(84,   "RSI sell threshold",  input.integer,   0, 100, 1),
    STO_K       = input(65,   "Stochastic %K",       input.integer,   2, 100, 1),
    STO_KS      = input(1,    "Stochastic smooth",   input.integer,   1, 10, 1),
    STO_D       = input(10,   "Stochastic %D",       input.integer,   1, 10, 1),
    STO_OS      = input(39.0, "Stochastic oversold", input.double,    0, 100, 0.1),
    STO_OB      = input(48.1, "Stochastic overbought",input.double,    0, 100, 0.1),
    CCI_PER     = input(62,   "CCI period",          input.integer,   2, 100, 1),
    CCI_LOWER   = input(-102, "CCI lower",           input.integer, -200,   0, 1),
    CCI_UPPER   = input(185,  "CCI upper",           input.integer,    0, 200, 1),
    ROC_PER     = input(26,   "ROC period",          input.integer,   2, 100, 1),
    CMO_PER     = input(32,   "CMO period",          input.integer,   2, 100, 1),
    ATR_PER     = input(70,   "ATR period",          input.integer,   2, 100, 1),
    KC_PER      = input(57,   "KC MA period",        input.integer,   2, 100, 1),
    KC_MULT     = input(1.45, "KC multiplier",       input.double,    0.1, 5, 0.01),
    MACD_FAST   = input(22,   "MACD fast",           input.integer,   2, 100, 1),
    MACD_SLOW   = input(193,  "MACD slow",           input.integer,   2, 200, 1),
    MACD_SIG    = input(2,    "MACD signal",         input.integer,   2, 100, 1),
    PSAR_STEP   = input(0.046,"PSAR step",          input.double,  0.001, 1, 0.001),
    PSAR_MAX    = input(0.955,"PSAR max",           input.double,   0.1,  1, 0.001)
}
